---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    get:
      summary: List all users
      tags:
      - Users
      responses:
        '200':
          description: Users retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/User"
    post:
      summary: Create a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: User created
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/User"
  "/users/{id}":
    get:
      summary: Retrieve a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User retrieved
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '404':
          description: User not found
    put:
      summary: Update a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User updated
        '404':
          description: User not found
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/User"
    delete:
      summary: Delete a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: User deleted
        '404':
          description: User not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string
        appointment:
          type: string
          format: date_time
        assigned_to:
          type: integer
        role_code:
          type: string
        role_id:
          type: integer
      required:
      - first_name
      - last_name
      - email
